/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AppWatchRouteImport } from './pages/_app/watch'
import { Route as AppElectionsRouteImport } from './pages/_app/elections'
import { Route as AppBeginRouteImport } from './pages/_app/begin'
import { Route as AuthDashboardLayoutRouteImport } from './pages/_auth/_dashboard/layout'
import { Route as AuthDashboardVotesRouteImport } from './pages/_auth/_dashboard/votes'
import { Route as AuthDashboardVoteRegistryRouteImport } from './pages/_auth/_dashboard/vote-registry'
import { Route as AuthDashboardRoundRouteImport } from './pages/_auth/_dashboard/round'
import { Route as AuthDashboardMembersRouteImport } from './pages/_auth/_dashboard/members'
import { Route as AuthDashboardElectionRouteImport } from './pages/_auth/_dashboard/election'
import { Route as AuthDashboardElectedRouteImport } from './pages/_auth/_dashboard/elected'
import { Route as AppVoteElectionIdRouteImport } from './pages/_app/vote/$electionId'
import { Route as AppRoundsElectionIdRouteImport } from './pages/_app/rounds/$electionId'
import { Route as AppVoteElectionIdRoundIdRouteImport } from './pages/_app/vote/$electionId/$roundId'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppElectionsRoute = AppElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBeginRoute = AppBeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthDashboardLayoutRoute = AuthDashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthDashboardVotesRoute = AuthDashboardVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => AuthDashboardLayoutRoute,
} as any)
const AuthDashboardVoteRegistryRoute =
  AuthDashboardVoteRegistryRouteImport.update({
    id: '/vote-registry',
    path: '/vote-registry',
    getParentRoute: () => AuthDashboardLayoutRoute,
  } as any)
const AuthDashboardRoundRoute = AuthDashboardRoundRouteImport.update({
  id: '/round',
  path: '/round',
  getParentRoute: () => AuthDashboardLayoutRoute,
} as any)
const AuthDashboardMembersRoute = AuthDashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthDashboardLayoutRoute,
} as any)
const AuthDashboardElectionRoute = AuthDashboardElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => AuthDashboardLayoutRoute,
} as any)
const AuthDashboardElectedRoute = AuthDashboardElectedRouteImport.update({
  id: '/elected',
  path: '/elected',
  getParentRoute: () => AuthDashboardLayoutRoute,
} as any)
const AppVoteElectionIdRoute = AppVoteElectionIdRouteImport.update({
  id: '/vote/$electionId',
  path: '/vote/$electionId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRoundsElectionIdRoute = AppRoundsElectionIdRouteImport.update({
  id: '/rounds/$electionId',
  path: '/rounds/$electionId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppVoteElectionIdRoundIdRoute =
  AppVoteElectionIdRoundIdRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => AppVoteElectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/begin': typeof AppBeginRoute
  '/elections': typeof AppElectionsRoute
  '/watch': typeof AppWatchRoute
  '/login': typeof AuthLoginRoute
  '/rounds/$electionId': typeof AppRoundsElectionIdRoute
  '/vote/$electionId': typeof AppVoteElectionIdRouteWithChildren
  '/elected': typeof AuthDashboardElectedRoute
  '/election': typeof AuthDashboardElectionRoute
  '/members': typeof AuthDashboardMembersRoute
  '/round': typeof AuthDashboardRoundRoute
  '/vote-registry': typeof AuthDashboardVoteRegistryRoute
  '/votes': typeof AuthDashboardVotesRoute
  '/vote/$electionId/$roundId': typeof AppVoteElectionIdRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/begin': typeof AppBeginRoute
  '/elections': typeof AppElectionsRoute
  '/watch': typeof AppWatchRoute
  '/login': typeof AuthLoginRoute
  '/rounds/$electionId': typeof AppRoundsElectionIdRoute
  '/vote/$electionId': typeof AppVoteElectionIdRouteWithChildren
  '/elected': typeof AuthDashboardElectedRoute
  '/election': typeof AuthDashboardElectionRoute
  '/members': typeof AuthDashboardMembersRoute
  '/round': typeof AuthDashboardRoundRoute
  '/vote-registry': typeof AuthDashboardVoteRegistryRoute
  '/votes': typeof AuthDashboardVotesRoute
  '/vote/$electionId/$roundId': typeof AppVoteElectionIdRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_auth/_dashboard': typeof AuthDashboardLayoutRouteWithChildren
  '/_app/begin': typeof AppBeginRoute
  '/_app/elections': typeof AppElectionsRoute
  '/_app/watch': typeof AppWatchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/rounds/$electionId': typeof AppRoundsElectionIdRoute
  '/_app/vote/$electionId': typeof AppVoteElectionIdRouteWithChildren
  '/_auth/_dashboard/elected': typeof AuthDashboardElectedRoute
  '/_auth/_dashboard/election': typeof AuthDashboardElectionRoute
  '/_auth/_dashboard/members': typeof AuthDashboardMembersRoute
  '/_auth/_dashboard/round': typeof AuthDashboardRoundRoute
  '/_auth/_dashboard/vote-registry': typeof AuthDashboardVoteRegistryRoute
  '/_auth/_dashboard/votes': typeof AuthDashboardVotesRoute
  '/_app/vote/$electionId/$roundId': typeof AppVoteElectionIdRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/begin'
    | '/elections'
    | '/watch'
    | '/login'
    | '/rounds/$electionId'
    | '/vote/$electionId'
    | '/elected'
    | '/election'
    | '/members'
    | '/round'
    | '/vote-registry'
    | '/votes'
    | '/vote/$electionId/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/begin'
    | '/elections'
    | '/watch'
    | '/login'
    | '/rounds/$electionId'
    | '/vote/$electionId'
    | '/elected'
    | '/election'
    | '/members'
    | '/round'
    | '/vote-registry'
    | '/votes'
    | '/vote/$electionId/$roundId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/_dashboard'
    | '/_app/begin'
    | '/_app/elections'
    | '/_app/watch'
    | '/_auth/login'
    | '/_app/'
    | '/_app/rounds/$electionId'
    | '/_app/vote/$electionId'
    | '/_auth/_dashboard/elected'
    | '/_auth/_dashboard/election'
    | '/_auth/_dashboard/members'
    | '/_auth/_dashboard/round'
    | '/_auth/_dashboard/vote-registry'
    | '/_auth/_dashboard/votes'
    | '/_app/vote/$electionId/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/elections': {
      id: '/_app/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof AppElectionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/begin': {
      id: '/_app/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof AppBeginRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/_dashboard': {
      id: '/_auth/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthDashboardLayoutRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_dashboard/votes': {
      id: '/_auth/_dashboard/votes'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof AuthDashboardVotesRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_auth/_dashboard/vote-registry': {
      id: '/_auth/_dashboard/vote-registry'
      path: '/vote-registry'
      fullPath: '/vote-registry'
      preLoaderRoute: typeof AuthDashboardVoteRegistryRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_auth/_dashboard/round': {
      id: '/_auth/_dashboard/round'
      path: '/round'
      fullPath: '/round'
      preLoaderRoute: typeof AuthDashboardRoundRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_auth/_dashboard/members': {
      id: '/_auth/_dashboard/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthDashboardMembersRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_auth/_dashboard/election': {
      id: '/_auth/_dashboard/election'
      path: '/election'
      fullPath: '/election'
      preLoaderRoute: typeof AuthDashboardElectionRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_auth/_dashboard/elected': {
      id: '/_auth/_dashboard/elected'
      path: '/elected'
      fullPath: '/elected'
      preLoaderRoute: typeof AuthDashboardElectedRouteImport
      parentRoute: typeof AuthDashboardLayoutRoute
    }
    '/_app/vote/$electionId': {
      id: '/_app/vote/$electionId'
      path: '/vote/$electionId'
      fullPath: '/vote/$electionId'
      preLoaderRoute: typeof AppVoteElectionIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/rounds/$electionId': {
      id: '/_app/rounds/$electionId'
      path: '/rounds/$electionId'
      fullPath: '/rounds/$electionId'
      preLoaderRoute: typeof AppRoundsElectionIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/vote/$electionId/$roundId': {
      id: '/_app/vote/$electionId/$roundId'
      path: '/$roundId'
      fullPath: '/vote/$electionId/$roundId'
      preLoaderRoute: typeof AppVoteElectionIdRoundIdRouteImport
      parentRoute: typeof AppVoteElectionIdRoute
    }
  }
}

interface AppVoteElectionIdRouteChildren {
  AppVoteElectionIdRoundIdRoute: typeof AppVoteElectionIdRoundIdRoute
}

const AppVoteElectionIdRouteChildren: AppVoteElectionIdRouteChildren = {
  AppVoteElectionIdRoundIdRoute: AppVoteElectionIdRoundIdRoute,
}

const AppVoteElectionIdRouteWithChildren =
  AppVoteElectionIdRoute._addFileChildren(AppVoteElectionIdRouteChildren)

interface AppLayoutRouteChildren {
  AppBeginRoute: typeof AppBeginRoute
  AppElectionsRoute: typeof AppElectionsRoute
  AppWatchRoute: typeof AppWatchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRoundsElectionIdRoute: typeof AppRoundsElectionIdRoute
  AppVoteElectionIdRoute: typeof AppVoteElectionIdRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppBeginRoute: AppBeginRoute,
  AppElectionsRoute: AppElectionsRoute,
  AppWatchRoute: AppWatchRoute,
  AppIndexRoute: AppIndexRoute,
  AppRoundsElectionIdRoute: AppRoundsElectionIdRoute,
  AppVoteElectionIdRoute: AppVoteElectionIdRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthDashboardLayoutRouteChildren {
  AuthDashboardElectedRoute: typeof AuthDashboardElectedRoute
  AuthDashboardElectionRoute: typeof AuthDashboardElectionRoute
  AuthDashboardMembersRoute: typeof AuthDashboardMembersRoute
  AuthDashboardRoundRoute: typeof AuthDashboardRoundRoute
  AuthDashboardVoteRegistryRoute: typeof AuthDashboardVoteRegistryRoute
  AuthDashboardVotesRoute: typeof AuthDashboardVotesRoute
}

const AuthDashboardLayoutRouteChildren: AuthDashboardLayoutRouteChildren = {
  AuthDashboardElectedRoute: AuthDashboardElectedRoute,
  AuthDashboardElectionRoute: AuthDashboardElectionRoute,
  AuthDashboardMembersRoute: AuthDashboardMembersRoute,
  AuthDashboardRoundRoute: AuthDashboardRoundRoute,
  AuthDashboardVoteRegistryRoute: AuthDashboardVoteRegistryRoute,
  AuthDashboardVotesRoute: AuthDashboardVotesRoute,
}

const AuthDashboardLayoutRouteWithChildren =
  AuthDashboardLayoutRoute._addFileChildren(AuthDashboardLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthDashboardLayoutRoute: typeof AuthDashboardLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthDashboardLayoutRoute: AuthDashboardLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
